# Generated by Django 5.1 on 2024-08-24 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_service_image_servicecategory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecategory',
            name='description',
        ),
    ]
